require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/bundle'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
  
Rails/Output:
  Exclude:
    - 'db/seeds.rb'

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false